version: '3'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - php

    postgres:
        image: postgres:11-alpine
        command: postgres -c work_mem=100MB -c max_parallel_workers_per_gather=6
        shm_size: 5g
        ports:
            - '5432:5432'
        container_name: 'postgresql_alpine'
        working_dir: /app
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            LC_COLLATE: 'sv_SE.UTF-8'
            LC_CTYPE: 'sv_SE.UTF-8'
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        networks:
            - php

    rabbitmq:
        image: rabbitmq:3.7.5-management
        hostname: rabbit-mq
        container_name: 'rabbit-mq'
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        networks:
            - php

    redis:
        container_name: container_redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - php

    redis_cache:
        container_name: container_redis_cache
        image: redis:alpine
        ports:
            - "6380:6379"
        networks:
            - php

    php:
        container_name: php-fpm
        build: ./php-fpm
        ports:
            - "9000:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - redis
        depends_on: 
            - db
        networks:
            - php

    php-consume-csv-first:
        container_name: php-consume-csv-first
        build: php-consume-csv
        ports:
            - "9002:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-csv/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-csv-second:
        container_name: php-consume-csv-second
        build: php-consume-csv
        ports:
            - "9003:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-csv/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-csv-carriage:
        container_name: php-consume-csv-carriage
        build: php-consume-csv-carriage
        ports:
            - "9004:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-csv-carriage/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adraction-first:
        container_name: php-consume-adraction-first
        build: php-consume-adraction
        ports:
            - "9005:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adraction/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adraction-second:
        container_name: php-consume-adraction-second
        build: php-consume-adraction
        ports:
            - "9006:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adraction/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adrecord-first:
        container_name: php-consume-adrecord-first
        build: php-consume-adrecord
        ports:
            - "9007:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adrecord/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adrecord-second:
        container_name: php-consume-adrecord-second
        build: php-consume-adrecord
        ports:
            - "9008:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adrecord/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
        networks:
            elk_stack:
                aliases:
                    - "elasticsearch"
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.4.2
        depends_on: 
            - elasticsearch
        volumes:
            - ./elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
        networks:
            - elk_stack
    kibana:
        container_name: kibana
        depends_on: 
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.4.2
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elk_stack
        ports:
            - "81:5601"

networks:
    php:
    elk_stack:
