version: '3'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data/mysql/:/var/lib/mysql
        networks:
            - php

    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./docker/mongodb/mongod.conf:/etc/mongod.conf
            - ./docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./data/momgo/:/data/db/
            - ./docker/mongodb/data/log/:/var/log/mongodb/
            - ./docker/mongodb/home:/home/mongodb
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"
        command: ["-f", "/etc/mongod.conf"]
        networks:
            - php

    postgres:
        image: postgres:11-alpine
        command: postgres -c work_mem=4GB -c max_parallel_workers_per_gather=8 -c max_connections=900
        shm_size: 8g
        ports:
            - '5432:5432'
        container_name: 'postgresql_alpine'
        working_dir: /app
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            LC_COLLATE: 'sv_SE.UTF-8'
            LC_CTYPE: 'sv_SE.UTF-8'
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
            - ./pg/thesaurus_my_swedish.ths:/usr/local/share/postgresql/tsearch_data/thesaurus_my_swedish.ths
        networks:
            - php

    rabbitmq:
        image: rabbitmq:3.7.5-management
        hostname: rabbit-mq
        container_name: 'rabbit-mq'
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        networks:
            - php

    redis:
        container_name: container_redis
        image: redis:alpine
        command:
            - 'redis-server'
            - '--maxmemory-policy allkeys-lru'
        ports:
            - "6381:6379"
        networks:
            - php

    redis_cache:
        container_name: container_redis_cache
        image: redis:alpine
        command:
            - 'redis-server'
            - '--maxmemory-policy allkeys-lru'
        ports:
            - "6380:6379"
        networks:
            - php

    php:
        container_name: php-fpm
        build: ./php-fpm
        ports:
            - "9000:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - redis
        depends_on: 
            - db
        networks:
            - php

    php-consume-csv-first:
        container_name: php-consume-csv-first
        build: php-consume-csv
        ports:
            - "9002:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-csv/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-csv-second:
      container_name: php-consume-csv-second
      build: php-consume-csv
      ports:
        - "9003:9001"
      environment: # You can use this section to set environment variables. But you can also use the .env file.
        - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
      volumes:
        - ./symfony:/var/www/symfony:cached
        - ./logs/symfony:/var/www/symfony/var/log:cached
        - ./php-consume-csv/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
      links:
        - redis
      depends_on:
        - db
      networks:
        - php

    php-consume-csv-third:
      container_name: php-consume-csv-third
      build: php-consume-csv
      ports:
        - "9004:9001"
      environment: # You can use this section to set environment variables. But you can also use the .env file.
        - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
      volumes:
        - ./symfony:/var/www/symfony:cached
        - ./logs/symfony:/var/www/symfony/var/log:cached
        - ./php-consume-csv/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
      links:
        - redis
      depends_on:
        - db
      networks:
        - php

    php-consume-csv-fourth:
      container_name: php-consume-csv-fourth
      build: php-consume-csv
      ports:
        - "9005:9001"
      environment: # You can use this section to set environment variables. But you can also use the .env file.
        - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
      volumes:
        - ./symfony:/var/www/symfony:cached
        - ./logs/symfony:/var/www/symfony/var/log:cached
        - ./php-consume-csv/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
      links:
        - redis
      depends_on:
        - db
      networks:
        - php

    php-consume-csv-carriage:
        container_name: php-consume-csv-carriage
        build: php-consume-csv-carriage
        ports:
            - "9006:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-csv-carriage/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adraction-first:
        container_name: php-consume-adraction-first
        build: php-consume-adraction
        ports:
            - "9007:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adraction/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adraction-second:
        container_name: php-consume-adraction-second
        build: php-consume-adraction
        ports:
            - "9008:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adraction/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-adrecord-first:
        container_name: php-consume-adrecord-first
        build: php-consume-adrecord
        ports:
            - "9009:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-adrecord/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-awin-first:
        container_name: php-consume-awin-first
        build: php-consume-awin
        ports:
            - "9010:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-awin/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-awin-second:
        container_name: php-consume-awin-second
        build: php-consume-awin
        ports:
            - "9011:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-awin/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-awin-third:
        container_name: php-consume-awin-third
        build: php-consume-awin
        ports:
            - "9012:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-awin/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-trade-doubler-first:
        container_name: php-consume-trade-doubler-first
        build: php-consume-trade-doubler
        ports:
            - "9013:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-trade-doubler/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-trade-doubler-second:
        container_name: php-consume-trade-doubler-second
        build: php-consume-trade-doubler
        ports:
            - "9014:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-trade-doubler/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-trade-doubler-third:
        container_name: php-consume-trade-doubler-third
        build: php-consume-trade-doubler
        ports:
            - "9015:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-trade-doubler/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-csv-vacuum:
        container_name: php-consume-csv-vacuum
        build: php-consume-csv-vacuum
        ports:
            - "9016:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-csv-vacuum/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    php-consume-manually-resource:
        container_name: php-consume-manually-resource
        build: php-consume-manually-resource
        ports:
            - "9017:9001"
        environment: # You can use this section to set environment variables. But you can also use the .env file.
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN} # AMQP connection string-
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./php-consume-manually-resource/supervisord.conf:/etc/supervisord/conf.d/supervisord.conf
        links:
            - redis
        depends_on:
            - db
        networks:
            - php

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
        networks:
            elk_stack:
                aliases:
                    - "elasticsearch"
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.4.2
        depends_on:
            - elasticsearch
        volumes:
            - ./elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
        networks:
            - elk_stack
    kibana:
        container_name: kibana
        depends_on: 
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.4.2
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elk_stack
        ports:
            - "81:5601"

networks:
    php:
    elk_stack:
